version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "group-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15r91rpv9vcz9"
s3_prefix = "group-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
